apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
  labels:
{{ include "mysql-labels" . | indent 4 }}
spec:
  accessModes:
  - {{ .Values.Persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.Persistence.pvcStorageSize }}