
apiVersion: v1
kind: Service
metadata:
  name: redis  #Service name should be redis else voteapp fails to connect 
spec:
  type: {{ .Values.ports.redis.type }}
  selector:
{{ include "redis-labels" . | indent 4}}
  ports:
  {{- with .Values.ports.redis }}
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end }}