apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vote-svc
spec:
  type: {{ .Values.ports.vote.type }}
  selector:
{{ include "vote-labels" . | indent 4}}
  ports:
  {{- with .Values.ports.vote }}
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
    nodePort: {{ .nodePort }}
  {{- end }}
